# Generated by Django 2.2 on 2020-05-04 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200504_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author'),
        ),
    ]
